---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: timestampsFlag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: in-array
          operands:
            - asd
    flagValue: false
